# [AI GENERATED] LLM: GitHub Copilot, Mode: Chat, Date: 2025-09-24
{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "school-microservice.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "school-microservice.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "school-microservice.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- toYaml .Values.networkPolicy.policyTypes | nindent 4 }}
  {{- if .Values.networkPolicy.ingress }}
  ingress:
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
  {{- end }}
  {{- if .Values.networkPolicy.egress }}
  egress:
    {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
  {{- end }}
{{- end }}