# [AI GENERATED] LLM: GitHub Copilot, Mode: Chat, Date: 2025-09-24
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "school-microservice.fullname" . }}-couchbase-secret
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "school-microservice.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.secrets.couchbase.username | b64enc | quote }}
  password: {{ .Values.secrets.couchbase.password | b64enc | quote }}